;;; blue-theme-support.el --- Neovim blue theme face mappings -*- lexical-binding: t; -*-

;; Neovim blue-specific palette role choices and face mappings.  The generic
;; `chief-theme-kit.el' deliberately contains no theme policy; this file owns the
;; decisions that make the local theme track Neovim's blue colorscheme while
;; covering Emacs UI, syntax, tree-sitter, terminal, completion, and Git faces.

(eval-and-compile
  (unless (fboundp 'chief-theme-kit-color)
    (let* ((support-file (or load-file-name buffer-file-name))
           (support-directory (and support-file (file-name-directory support-file)))
           (candidates (delq nil
                             (list (and support-directory
                                        (expand-file-name "chief-theme-kit.el" support-directory))
                                   (expand-file-name "chief-theme-kit.el" default-directory)
                                   (expand-file-name "themes/chief-theme-kit.el" default-directory))))
           (kit-file (catch 'found
                       (dolist (candidate candidates)
                         (when (file-readable-p candidate)
                           (throw 'found candidate))))))
      (unless kit-file
        (error "Unable to locate chief-theme-kit.el for blue-theme-support"))
      (load kit-file nil t))))

(declare-function chief-theme-kit-apply "chief-theme-kit" (theme faces &optional variables))

(defun blue-theme--faces (palette)
  "Return Neovim blue face specs derived from PALETTE."
  (chief-theme-kit-with-colors palette
      (bg fg surface surface-variant element hover border color-column
          cursor cursor-fg cursor-im comment conceal constant directory error error-bg
          error-message-bg fold-column folded-fg folded-bg identifier ignored
          inc-search-fg inc-search-bg label line-number mode-message-fg mode-message-bg
          nontext menu-fg menu-bg menu-match-fg menu-selection-fg menu-selection-bg
          preproc quickfix-fg quickfix-bg search-fg search-bg sign-column special
          status-fg status-bg status-inactive-bg title titlebar-bg titlebar-nc-bg
          titlebar-nc-fg toolbar-bg type visual-fg visual-bg visual-nos-fg visual-nos-bg
          warning wild-menu-fg wild-menu-bg diff-add-bg diff-change-bg diff-delete-bg
          diff-text-bg inlay-bg inverse-fg
          ansi-black ansi-red ansi-green ansi-yellow ansi-blue ansi-magenta ansi-cyan
          ansi-white ansi-bright-black ansi-bright-red ansi-bright-green
          ansi-bright-yellow ansi-bright-blue ansi-bright-magenta ansi-bright-cyan
          ansi-bright-white)
    `((default ((t (:background ,bg :foreground ,fg))))
      (cursor ((t (:background ,cursor :foreground ,cursor-fg))))
      (secondary-cursor ((t (:background ,cursor-im :foreground ,cursor-fg))))
      (fringe ((t (:background ,bg :foreground ,sign-column))))
      (region ((t (:background ,visual-bg :foreground ,visual-fg :extend t))))
      (secondary-selection ((t (:background ,visual-nos-bg :foreground ,visual-nos-fg :extend t))))
      (highlight ((t (:background ,hover :foreground ,fg :extend t))))
      (hl-line ((t (:background ,hover :extend t))))
      (line-number ((t (:background ,bg :foreground ,line-number))))
      (line-number-current-line ((t (:background ,hover :foreground ,fg :weight bold))))
      (line-number-major-tick ((t (:background ,bg :foreground ,fold-column))))
      (line-number-minor-tick ((t (:background ,bg :foreground ,fold-column))))
      (vertical-border ((t (:foreground ,border))))
      (window-divider ((t (:foreground ,border))))
      (window-divider-first-pixel ((t (:foreground ,border))))
      (window-divider-last-pixel ((t (:foreground ,border))))
      (internal-border ((t (:background ,border))))
      (child-frame-border ((t (:background ,border))))
      (fill-column-indicator ((t (:foreground ,color-column))))
      (shadow ((t (:foreground ,ignored))))
      (escape-glyph ((t (:foreground ,nontext))))
      (homoglyph ((t (:foreground ,nontext))))
      (nobreak-space ((t (:foreground ,nontext :underline t))))
      (success ((t (:foreground ,preproc :weight bold))))
      (warning ((t (:foreground ,warning :weight bold))))
      (error ((t (:background ,error-bg :foreground ,error :weight bold))))
      (link ((t (:foreground ,directory :underline t))))
      (link-visited ((t (:foreground ,special :underline t))))
      (button ((t (:foreground ,directory :underline t))))
      (tooltip ((t (:background ,element :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tool-bar ((t (:background ,toolbar-bg :foreground ,visual-fg :box (:line-width -1 :color ,border)))))
      (folded-face ((t (:background ,folded-bg :foreground ,folded-fg))))
      (fold-this-overlay ((t (:background ,folded-bg :foreground ,folded-fg))))
      (hideshow-folded-face ((t (:background ,folded-bg :foreground ,folded-fg))))

      (mode-line ((t (:background ,status-bg :foreground ,status-fg :box (:line-width -1 :color ,status-bg)))))
      (mode-line-active ((t (:background ,status-bg :foreground ,status-fg :box (:line-width -1 :color ,status-bg)))))
      (mode-line-inactive ((t (:background ,status-inactive-bg :foreground ,status-fg :box (:line-width -1 :color ,status-inactive-bg)))))
      (mode-line-buffer-id ((t (:foreground ,status-fg :weight bold))))
      (mode-line-emphasis ((t (:background ,mode-message-bg :foreground ,mode-message-fg :weight bold))))
      (mode-line-highlight ((t (:background ,wild-menu-bg :foreground ,wild-menu-fg :box nil))))
      (header-line ((t (:background ,titlebar-bg :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tab-bar ((t (:background ,surface-variant :foreground ,fg))))
      (tab-bar-tab ((t (:background ,titlebar-bg :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tab-bar-tab-inactive ((t (:background ,titlebar-nc-bg :foreground ,titlebar-nc-fg :box (:line-width -1 :color ,border)))))
      (tab-line ((t (:background ,surface-variant :foreground ,fg))))
      (tab-line-tab ((t (:background ,titlebar-bg :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tab-line-tab-current ((t (:background ,titlebar-bg :foreground ,fg :box (:line-width -1 :color ,fg)))))
      (tab-line-tab-inactive ((t (:background ,titlebar-nc-bg :foreground ,titlebar-nc-fg :box (:line-width -1 :color ,border)))))
      (tab-line-highlight ((t (:background ,wild-menu-bg :foreground ,wild-menu-fg))))

      (minibuffer-prompt ((t (:foreground ,preproc :weight bold))))
      (completions-annotations ((t (:foreground ,comment))))
      (completions-common-part ((t (:foreground ,menu-match-fg :weight bold))))
      (completions-first-difference ((t (:foreground ,special :weight bold))))
      (completions-highlight ((t (:background ,menu-selection-bg :foreground ,menu-selection-fg))))
      (next-error ((t (:background ,quickfix-bg :foreground ,quickfix-fg))))
      (match ((t (:background ,search-bg :foreground ,search-fg :weight bold))))
      (isearch ((t (:background ,inc-search-bg :foreground ,inc-search-fg :weight bold))))
      (isearch-fail ((t (:background ,error-message-bg :foreground ,ansi-bright-white :weight bold))))
      (lazy-highlight ((t (:background ,search-bg :foreground ,search-fg))))
      (query-replace ((t (:inherit isearch))))
      (show-paren-match ((t (:background ,visual-bg :foreground ,visual-fg :weight bold))))
      (show-paren-mismatch ((t (:background ,error-message-bg :foreground ,ansi-bright-white :weight bold))))
      (trailing-whitespace ((t (:background ,error-message-bg))))
      (whitespace-space ((t (:foreground ,border))))
      (whitespace-tab ((t (:foreground ,border))))
      (whitespace-trailing ((t (:background ,error-message-bg :foreground ,ansi-bright-white))))
      (eldoc-highlight-function-argument ((t (:foreground ,special :weight bold))))

      ;; Neovim blue syntax mapping.
      (font-lock-builtin-face ((t (:foreground ,preproc))))
      (font-lock-comment-face ((t (:foreground ,comment :weight bold))))
      (font-lock-comment-delimiter-face ((t (:foreground ,comment :weight bold))))
      (font-lock-constant-face ((t (:foreground ,constant))))
      (font-lock-doc-face ((t (:foreground ,comment))))
      (font-lock-doc-markup-face ((t (:foreground ,conceal))))
      (font-lock-function-name-face ((t (:foreground ,identifier))))
      (font-lock-function-call-face ((t (:foreground ,identifier))))
      (font-lock-keyword-face ((t (:foreground ,ansi-bright-white))))
      (font-lock-negation-char-face ((t (:foreground ,type :weight bold))))
      (font-lock-preprocessor-face ((t (:foreground ,preproc))))
      (font-lock-regexp-face ((t (:foreground ,constant))))
      (font-lock-regexp-grouping-backslash ((t (:foreground ,special))))
      (font-lock-regexp-grouping-construct ((t (:foreground ,special))))
      (font-lock-string-face ((t (:foreground ,constant))))
      (font-lock-type-face ((t (:foreground ,type :weight bold))))
      (font-lock-variable-name-face ((t (:foreground ,identifier))))
      (font-lock-variable-use-face ((t (:foreground ,fg))))
      (font-lock-warning-face ((t (:foreground ,warning :weight bold))))
      (font-lock-escape-face ((t (:foreground ,special))))
      (font-lock-number-face ((t (:foreground ,constant))))
      (font-lock-operator-face ((t (:foreground ,type :weight bold))))
      (font-lock-property-name-face ((t (:foreground ,label))))
      (font-lock-property-use-face ((t (:foreground ,label))))
      (font-lock-bracket-face ((t (:foreground ,special))))
      (font-lock-delimiter-face ((t (:foreground ,special))))
      (font-lock-punctuation-face ((t (:foreground ,special))))
      (font-lock-misc-punctuation-face ((t (:foreground ,special))))

      ;; Tree-sitter capture faces used by tree-sitter based modes/packages.
      (tree-sitter-hl-face:attribute ((t (:foreground ,special))))
      (tree-sitter-hl-face:boolean ((t (:foreground ,constant))))
      (tree-sitter-hl-face:comment ((t (:foreground ,comment :weight bold))))
      (tree-sitter-hl-face:comment.doc ((t (:foreground ,comment))))
      (tree-sitter-hl-face:constant ((t (:foreground ,constant))))
      (tree-sitter-hl-face:constant.builtin ((t (:foreground ,constant))))
      (tree-sitter-hl-face:constructor ((t (:foreground ,type :weight bold))))
      (tree-sitter-hl-face:embedded ((t (:foreground ,fg))))
      (tree-sitter-hl-face:emphasis ((t (:foreground ,fg :slant italic))))
      (tree-sitter-hl-face:emphasis.strong ((t (:foreground ,fg :weight bold))))
      (tree-sitter-hl-face:enum ((t (:foreground ,type :weight bold))))
      (tree-sitter-hl-face:escape ((t (:foreground ,special))))
      (tree-sitter-hl-face:function ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:function.builtin ((t (:foreground ,preproc))))
      (tree-sitter-hl-face:function.call ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:function.macro ((t (:foreground ,preproc))))
      (tree-sitter-hl-face:function.method ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:function.method.call ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:function.special ((t (:foreground ,special))))
      (tree-sitter-hl-face:hint ((t (:foreground ,ignored))))
      (tree-sitter-hl-face:keyword ((t (:foreground ,ansi-bright-white))))
      (tree-sitter-hl-face:label ((t (:foreground ,label))))
      (tree-sitter-hl-face:link_text ((t (:foreground ,directory :underline t))))
      (tree-sitter-hl-face:link_uri ((t (:foreground ,directory :underline t))))
      (tree-sitter-hl-face:method ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:method.call ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:number ((t (:foreground ,constant))))
      (tree-sitter-hl-face:operator ((t (:foreground ,type :weight bold))))
      (tree-sitter-hl-face:predictive ((t (:foreground ,ignored))))
      (tree-sitter-hl-face:preproc ((t (:foreground ,preproc))))
      (tree-sitter-hl-face:primary ((t (:foreground ,fg))))
      (tree-sitter-hl-face:property ((t (:foreground ,label))))
      (tree-sitter-hl-face:property.definition ((t (:foreground ,label))))
      (tree-sitter-hl-face:punctuation ((t (:foreground ,special))))
      (tree-sitter-hl-face:punctuation.bracket ((t (:foreground ,special))))
      (tree-sitter-hl-face:punctuation.delimiter ((t (:foreground ,special))))
      (tree-sitter-hl-face:punctuation.list_marker ((t (:foreground ,special))))
      (tree-sitter-hl-face:punctuation.special ((t (:foreground ,special))))
      (tree-sitter-hl-face:string ((t (:foreground ,constant))))
      (tree-sitter-hl-face:string.escape ((t (:foreground ,special))))
      (tree-sitter-hl-face:string.regex ((t (:foreground ,constant))))
      (tree-sitter-hl-face:string.special ((t (:foreground ,special))))
      (tree-sitter-hl-face:string.special.symbol ((t (:foreground ,special))))
      (tree-sitter-hl-face:tag ((t (:foreground ,special))))
      (tree-sitter-hl-face:tag.doctype ((t (:foreground ,special))))
      (tree-sitter-hl-face:text.literal ((t (:foreground ,constant))))
      (tree-sitter-hl-face:title ((t (:foreground ,title))))
      (tree-sitter-hl-face:type ((t (:foreground ,type :weight bold))))
      (tree-sitter-hl-face:type.builtin ((t (:foreground ,type :weight bold))))
      (tree-sitter-hl-face:type.parameter ((t (:foreground ,type :weight bold))))
      (tree-sitter-hl-face:variable ((t (:foreground ,identifier))))
      (tree-sitter-hl-face:variable.builtin ((t (:foreground ,preproc))))
      (tree-sitter-hl-face:variable.parameter ((t (:foreground ,fg))))
      (tree-sitter-hl-face:variable.special ((t (:foreground ,special))))
      (tree-sitter-hl-face:variant ((t (:foreground ,label))))

      (ansi-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
      (ansi-color-red ((t (:foreground ,ansi-red :background ,ansi-red))))
      (ansi-color-green ((t (:foreground ,ansi-green :background ,ansi-green))))
      (ansi-color-yellow ((t (:foreground ,ansi-yellow :background ,ansi-yellow))))
      (ansi-color-blue ((t (:foreground ,ansi-blue :background ,ansi-blue))))
      (ansi-color-magenta ((t (:foreground ,ansi-magenta :background ,ansi-magenta))))
      (ansi-color-cyan ((t (:foreground ,ansi-cyan :background ,ansi-cyan))))
      (ansi-color-white ((t (:foreground ,ansi-white :background ,ansi-white))))
      (ansi-color-bright-black ((t (:foreground ,ansi-bright-black :background ,ansi-bright-black))))
      (ansi-color-bright-red ((t (:foreground ,ansi-bright-red :background ,ansi-bright-red))))
      (ansi-color-bright-green ((t (:foreground ,ansi-bright-green :background ,ansi-bright-green))))
      (ansi-color-bright-yellow ((t (:foreground ,ansi-bright-yellow :background ,ansi-bright-yellow))))
      (ansi-color-bright-blue ((t (:foreground ,ansi-bright-blue :background ,ansi-bright-blue))))
      (ansi-color-bright-magenta ((t (:foreground ,ansi-bright-magenta :background ,ansi-bright-magenta))))
      (ansi-color-bright-cyan ((t (:foreground ,ansi-bright-cyan :background ,ansi-bright-cyan))))
      (ansi-color-bright-white ((t (:foreground ,ansi-bright-white :background ,ansi-bright-white))))
      (term-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
      (term-color-red ((t (:foreground ,ansi-red :background ,ansi-red))))
      (term-color-green ((t (:foreground ,ansi-green :background ,ansi-green))))
      (term-color-yellow ((t (:foreground ,ansi-yellow :background ,ansi-yellow))))
      (term-color-blue ((t (:foreground ,ansi-blue :background ,ansi-blue))))
      (term-color-magenta ((t (:foreground ,ansi-magenta :background ,ansi-magenta))))
      (term-color-cyan ((t (:foreground ,ansi-cyan :background ,ansi-cyan))))
      (term-color-white ((t (:foreground ,ansi-white :background ,ansi-white))))
      (vterm-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
      (vterm-color-red ((t (:foreground ,ansi-red :background ,ansi-red))))
      (vterm-color-green ((t (:foreground ,ansi-green :background ,ansi-green))))
      (vterm-color-yellow ((t (:foreground ,ansi-yellow :background ,ansi-yellow))))
      (vterm-color-blue ((t (:foreground ,ansi-blue :background ,ansi-blue))))
      (vterm-color-magenta ((t (:foreground ,ansi-magenta :background ,ansi-magenta))))
      (vterm-color-cyan ((t (:foreground ,ansi-cyan :background ,ansi-cyan))))
      (vterm-color-white ((t (:foreground ,ansi-white :background ,ansi-white))))
      (vterm-color-bright-black ((t (:foreground ,ansi-bright-black :background ,ansi-bright-black))))
      (vterm-color-bright-red ((t (:foreground ,ansi-bright-red :background ,ansi-bright-red))))
      (vterm-color-bright-green ((t (:foreground ,ansi-bright-green :background ,ansi-bright-green))))
      (vterm-color-bright-yellow ((t (:foreground ,ansi-bright-yellow :background ,ansi-bright-yellow))))
      (vterm-color-bright-blue ((t (:foreground ,ansi-bright-blue :background ,ansi-bright-blue))))
      (vterm-color-bright-magenta ((t (:foreground ,ansi-bright-magenta :background ,ansi-bright-magenta))))
      (vterm-color-bright-cyan ((t (:foreground ,ansi-bright-cyan :background ,ansi-bright-cyan))))
      (vterm-color-bright-white ((t (:foreground ,ansi-bright-white :background ,ansi-bright-white))))
      (ghostel-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
      (ghostel-color-red ((t (:foreground ,ansi-red :background ,ansi-red))))
      (ghostel-color-green ((t (:foreground ,ansi-green :background ,ansi-green))))
      (ghostel-color-yellow ((t (:foreground ,ansi-yellow :background ,ansi-yellow))))
      (ghostel-color-blue ((t (:foreground ,ansi-blue :background ,ansi-blue))))
      (ghostel-color-magenta ((t (:foreground ,ansi-magenta :background ,ansi-magenta))))
      (ghostel-color-cyan ((t (:foreground ,ansi-cyan :background ,ansi-cyan))))
      (ghostel-color-white ((t (:foreground ,ansi-white :background ,ansi-white))))
      (ghostel-color-bright-black ((t (:foreground ,ansi-bright-black :background ,ansi-bright-black))))
      (ghostel-color-bright-red ((t (:foreground ,ansi-bright-red :background ,ansi-bright-red))))
      (ghostel-color-bright-green ((t (:foreground ,ansi-bright-green :background ,ansi-bright-green))))
      (ghostel-color-bright-yellow ((t (:foreground ,ansi-bright-yellow :background ,ansi-bright-yellow))))
      (ghostel-color-bright-blue ((t (:foreground ,ansi-bright-blue :background ,ansi-bright-blue))))
      (ghostel-color-bright-magenta ((t (:foreground ,ansi-bright-magenta :background ,ansi-bright-magenta))))
      (ghostel-color-bright-cyan ((t (:foreground ,ansi-bright-cyan :background ,ansi-bright-cyan))))
      (ghostel-color-bright-white ((t (:foreground ,ansi-bright-white :background ,ansi-bright-white))))
      (comint-highlight-prompt ((t (:foreground ,preproc :weight bold))))
      (comint-highlight-input ((t (:foreground ,fg))))
      (compilation-info ((t (:foreground ,quickfix-bg :weight bold))))
      (compilation-line-number ((t (:foreground ,quickfix-bg))))

      (dired-directory ((t (:foreground ,directory :weight bold))))
      (dired-symlink ((t (:foreground ,special))))
      (dired-flagged ((t (:foreground ,error :weight bold))))
      (dired-marked ((t (:foreground ,special :weight bold))))
      (dired-header ((t (:foreground ,title :weight bold))))
      (dired-ignored ((t (:foreground ,ignored))))

      (diff-added ((t (:background ,diff-add-bg :foreground ,ansi-bright-white :extend t))))
      (diff-removed ((t (:background ,diff-delete-bg :foreground ,ansi-bright-white :extend t))))
      (diff-changed ((t (:background ,diff-change-bg :foreground ,ansi-bright-white :extend t))))
      (diff-refine-added ((t (:background ,diff-text-bg :foreground ,inverse-fg))))
      (diff-refine-removed ((t (:background ,diff-text-bg :foreground ,inverse-fg))))
      (diff-refine-changed ((t (:background ,diff-text-bg :foreground ,inverse-fg))))
      (diff-header ((t (:background ,surface :foreground ,fg :extend t))))
      (diff-file-header ((t (:background ,surface :foreground ,directory :weight bold :extend t))))
      (diff-hunk-header ((t (:background ,element :foreground ,special :extend t))))
      (diff-hl-insert ((t (:foreground ,diff-add-bg :background ,diff-add-bg))))
      (diff-hl-delete ((t (:foreground ,diff-delete-bg :background ,diff-delete-bg))))
      (diff-hl-change ((t (:foreground ,diff-change-bg :background ,diff-change-bg))))
      (magit-section-heading ((t (:foreground ,title :weight bold))))
      (magit-section-highlight ((t (:background ,hover :extend t))))
      (magit-branch-local ((t (:foreground ,directory))))
      (magit-branch-remote ((t (:foreground ,preproc))))
      (magit-tag ((t (:foreground ,label))))
      (magit-hash ((t (:foreground ,ignored))))
      (magit-dimmed ((t (:foreground ,comment))))
      (magit-diff-file-heading ((t (:foreground ,directory :weight bold))))
      (magit-diff-hunk-heading ((t (:background ,element :foreground ,special :extend t))))
      (magit-diff-added ((t (:background ,diff-add-bg :foreground ,ansi-bright-white :extend t))))
      (magit-diff-removed ((t (:background ,diff-delete-bg :foreground ,ansi-bright-white :extend t))))

      (flycheck-error ((t (:underline (:style wave :color ,error-message-bg)))))
      (flycheck-warning ((t (:underline (:style wave :color ,warning)))))
      (flycheck-info ((t (:underline (:style wave :color ,directory)))))
      (flymake-error ((t (:underline (:style wave :color ,error-message-bg)))))
      (flymake-warning ((t (:underline (:style wave :color ,warning)))))
      (flymake-note ((t (:underline (:style wave :color ,directory)))))
      (lsp-face-highlight-read ((t (:background ,visual-bg :foreground ,visual-fg :extend t))))
      (lsp-face-highlight-write ((t (:background ,diff-add-bg :foreground ,ansi-bright-white :extend t))))
      (lsp-face-highlight-textual ((t (:background ,hover :extend t))))
      (lsp-inlay-hint-face ((t (:background ,inlay-bg :foreground ,comment :height 0.9))))
      (lsp-inlay-hint-parameter-face ((t (:background ,inlay-bg :foreground ,comment :height 0.9))))
      (lsp-inlay-hint-type-face ((t (:background ,inlay-bg :foreground ,comment :height 0.9))))
      (lsp-lens-face ((t (:foreground ,comment :height 0.85))))
      (lsp-face-semhl-comment ((t (:foreground ,comment :weight bold))))
      (lsp-face-semhl-function ((t (:foreground ,identifier))))
      (lsp-face-semhl-method ((t (:foreground ,identifier))))
      (lsp-face-semhl-macro ((t (:foreground ,preproc))))
      (lsp-face-semhl-keyword ((t (:foreground ,ansi-bright-white))))
      (lsp-face-semhl-operator ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-string ((t (:foreground ,constant))))
      (lsp-face-semhl-regexp ((t (:foreground ,constant))))
      (lsp-face-semhl-number ((t (:foreground ,constant))))
      (lsp-face-semhl-type ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-class ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-struct ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-interface ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-enum ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-type-parameter ((t (:foreground ,type :weight bold))))
      (lsp-face-semhl-variable ((t (:foreground ,identifier))))
      (lsp-face-semhl-parameter ((t (:foreground ,fg))))
      (lsp-face-semhl-property ((t (:foreground ,label))))
      (lsp-face-semhl-member ((t (:foreground ,label))))
      (lsp-face-semhl-event ((t (:foreground ,label))))
      (lsp-face-semhl-constant ((t (:foreground ,constant))))
      (lsp-face-semhl-namespace ((t (:foreground ,label))))
      (lsp-face-semhl-label ((t (:foreground ,label))))
      (lsp-face-semhl-default-library ((t (:foreground ,preproc))))
      (lsp-face-semhl-definition ((t (:foreground ,identifier :weight bold))))
      (lsp-face-semhl-implementation ((t (:foreground ,identifier :weight bold))))
      (lsp-face-semhl-static ((t (:foreground ,constant))))
      (lsp-face-semhl-deprecated ((t (:foreground ,ignored :strike-through t))))

      (vertico-current ((t (:background ,menu-selection-bg :foreground ,menu-selection-fg :extend t))))
      (vertico-group-title ((t (:foreground ,comment :slant italic))))
      (vertico-group-separator ((t (:foreground ,border :strike-through t))))
      (marginalia-documentation ((t (:foreground ,comment))))
      (marginalia-key ((t (:foreground ,label))))
      (marginalia-function ((t (:foreground ,identifier))))
      (marginalia-string ((t (:foreground ,constant))))
      (marginalia-number ((t (:foreground ,constant))))
      (consult-highlight-match ((t (:inherit match))))
      (consult-preview-match ((t (:inherit match))))
      (consult-separator ((t (:foreground ,border))))
      (orderless-match-face-0 ((t (:foreground ,menu-match-fg :weight bold))))
      (orderless-match-face-1 ((t (:foreground ,special :weight bold))))
      (orderless-match-face-2 ((t (:foreground ,preproc :weight bold))))
      (orderless-match-face-3 ((t (:foreground ,type :weight bold))))
      (which-key-key-face ((t (:foreground ,label :weight bold))))
      (which-key-command-description-face ((t (:foreground ,fg))))
      (which-key-group-description-face ((t (:foreground ,special))))
      (transient-heading ((t (:foreground ,title :weight bold))))
      (transient-key ((t (:foreground ,label :weight bold))))
      (transient-argument ((t (:foreground ,preproc))))
      (corfu-default ((t (:background ,menu-bg :foreground ,menu-fg))))
      (corfu-current ((t (:background ,menu-selection-bg :foreground ,menu-selection-fg))))
      (corfu-border ((t (:background ,border))))
      (company-tooltip ((t (:background ,menu-bg :foreground ,menu-fg))))
      (company-tooltip-selection ((t (:background ,menu-selection-bg :foreground ,menu-selection-fg))))

      (outline-1 ((t (:foreground ,title :weight bold))))
      (outline-2 ((t (:foreground ,label :weight bold))))
      (outline-3 ((t (:foreground ,directory :weight bold))))
      (outline-4 ((t (:foreground ,type :weight bold))))
      (outline-5 ((t (:foreground ,preproc :weight bold))))
      (outline-6 ((t (:foreground ,special :weight bold))))

      (rainbow-delimiters-depth-1-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-2-face ((t (:foreground ,special))))
      (rainbow-delimiters-depth-3-face ((t (:foreground ,constant))))
      (rainbow-delimiters-depth-4-face ((t (:foreground ,preproc))))
      (rainbow-delimiters-depth-5-face ((t (:foreground ,type))))
      (rainbow-delimiters-depth-6-face ((t (:foreground ,identifier))))
      (rainbow-delimiters-depth-7-face ((t (:foreground ,directory))))
      (rainbow-delimiters-depth-8-face ((t (:foreground ,label))))
      (rainbow-delimiters-depth-9-face ((t (:foreground ,comment))))
      (rainbow-delimiters-mismatched-face ((t (:foreground ,error :weight bold))))
      (rainbow-delimiters-unmatched-face ((t (:foreground ,error :weight bold)))))))

(defun blue-theme--variables (palette)
  "Return Neovim blue custom variable specs derived from PALETTE."
  (chief-theme-kit-with-colors palette
      (ansi-black ansi-red ansi-green ansi-yellow ansi-blue ansi-magenta ansi-cyan
       ansi-white)
    `((ansi-color-names-vector [,ansi-black ,ansi-red ,ansi-green ,ansi-yellow
                               ,ansi-blue ,ansi-magenta ,ansi-cyan ,ansi-white]))))

(defun blue-theme-apply (theme palette)
  "Apply Neovim blue face and variable specs for THEME from PALETTE."
  (chief-theme-kit-apply theme
                         (blue-theme--faces palette)
                         (blue-theme--variables palette)))

(provide 'blue-theme-support)

;;; blue-theme-support.el ends here
