;;; vercel-theme-support.el --- Vercel theme face mappings -*- lexical-binding: t; -*-

;; Vercel-specific palette role choices and face mappings.  The generic
;; `chief-theme-kit.el' deliberately contains no theme policy; this file owns the
;; decisions that make the local themes look like the Zed Vercel theme.

(eval-and-compile
  (unless (fboundp 'chief-theme-kit-color)
    (let* ((support-file (or load-file-name buffer-file-name))
           (support-directory (and support-file (file-name-directory support-file)))
           (candidates (delq nil
                             (list (and support-directory
                                        (expand-file-name "chief-theme-kit.el" support-directory))
                                   (expand-file-name "chief-theme-kit.el" default-directory)
                                   (expand-file-name "themes/chief-theme-kit.el" default-directory))))
           (kit-file (catch 'found
                       (dolist (candidate candidates)
                         (when (file-readable-p candidate)
                           (throw 'found candidate))))))
      (unless kit-file
        (error "Unable to locate chief-theme-kit.el for vercel-theme-support"))
      (load kit-file nil t))))

(declare-function chief-theme-kit-apply "chief-theme-kit" (theme faces &optional variables))

(defun vercel-theme--faces (palette)
  "Return Vercel face specs derived from PALETTE."
  (chief-theme-kit-with-colors palette
      (bg surface surface-variant element hover border fg muted line-number ignored
          black bright-black red green yellow blue magenta cyan white bright-white
          selection error-bg success-bg warning-bg hint-bg inverse-fg inlay-bg)
    `((default ((t (:background ,bg :foreground ,fg))))
      (cursor ((t (:background ,blue))))
      (fringe ((t (:background ,bg :foreground ,muted))))
      (region ((t (:background ,selection :extend t))))
      (secondary-selection ((t (:background ,hover :extend t))))
      (highlight ((t (:background ,hover :extend t))))
      (hl-line ((t (:background ,hover :extend t))))
      (line-number ((t (:background ,bg :foreground ,line-number))))
      (line-number-current-line ((t (:background ,bg :foreground ,fg :weight bold))))
      (vertical-border ((t (:foreground ,border))))
      (window-divider ((t (:foreground ,border))))
      (window-divider-first-pixel ((t (:foreground ,border))))
      (window-divider-last-pixel ((t (:foreground ,border))))
      (internal-border ((t (:background ,border))))
      (child-frame-border ((t (:background ,border))))
      (fill-column-indicator ((t (:foreground ,border))))
      (shadow ((t (:foreground ,muted))))
      (success ((t (:foreground ,green :weight bold))))
      (warning ((t (:foreground ,yellow :weight bold))))
      (error ((t (:foreground ,red :weight bold))))
      (link ((t (:foreground ,blue :underline t))))
      (link-visited ((t (:foreground ,magenta :underline t))))
      (button ((t (:foreground ,blue :underline t))))
      (tooltip ((t (:background ,element :foreground ,fg :box (:line-width -1 :color ,border)))))

      (mode-line ((t (:background ,surface :foreground ,fg :box (:line-width -1 :color ,border)))))
      (mode-line-active ((t (:background ,surface :foreground ,fg :box (:line-width -1 :color ,border)))))
      (mode-line-inactive ((t (:background ,surface-variant :foreground ,muted :box (:line-width -1 :color ,border)))))
      (mode-line-buffer-id ((t (:foreground ,blue :weight bold))))
      (mode-line-highlight ((t (:foreground ,blue :box nil))))
      (header-line ((t (:background ,surface :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tab-bar ((t (:background ,surface :foreground ,fg))))
      (tab-bar-tab ((t (:background ,surface :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tab-bar-tab-inactive ((t (:background ,surface-variant :foreground ,muted :box (:line-width -1 :color ,border)))))
      (tab-line ((t (:background ,surface :foreground ,fg))))
      (tab-line-tab ((t (:background ,surface :foreground ,fg :box (:line-width -1 :color ,border)))))
      (tab-line-tab-current ((t (:background ,surface :foreground ,fg :box (:line-width -1 :color ,blue)))))
      (tab-line-tab-inactive ((t (:background ,surface-variant :foreground ,muted :box (:line-width -1 :color ,border)))))
      (tab-line-highlight ((t (:background ,hover :foreground ,fg))))

      (minibuffer-prompt ((t (:foreground ,blue :weight bold))))
      (completions-annotations ((t (:foreground ,muted))))
      (completions-common-part ((t (:foreground ,blue :weight bold))))
      (completions-first-difference ((t (:foreground ,magenta :weight bold))))
      (completions-highlight ((t (:background ,hover :foreground ,fg))))
      (match ((t (:background ,selection :foreground ,fg :weight bold))))
      (isearch ((t (:background ,yellow :foreground ,inverse-fg :weight bold))))
      (isearch-fail ((t (:background ,error-bg :foreground ,red :weight bold))))
      (lazy-highlight ((t (:background ,warning-bg :foreground ,fg))))
      (query-replace ((t (:inherit isearch))))
      (show-paren-match ((t (:background ,selection :foreground ,fg :weight bold))))
      (show-paren-mismatch ((t (:background ,red :foreground ,inverse-fg :weight bold))))
      (trailing-whitespace ((t (:background ,red))))
      (whitespace-space ((t (:foreground ,hint-bg))))
      (whitespace-tab ((t (:foreground ,hint-bg))))
      (whitespace-trailing ((t (:background ,red :foreground ,inverse-fg))))
      (eldoc-highlight-function-argument ((t (:foreground ,magenta :weight bold))))

      ;; Zed Vercel syntax mapping.
      (font-lock-builtin-face ((t (:foreground ,magenta))))
      (font-lock-comment-face ((t (:foreground ,muted))))
      (font-lock-comment-delimiter-face ((t (:foreground ,muted))))
      (font-lock-constant-face ((t (:foreground ,blue))))
      (font-lock-doc-face ((t (:foreground ,green))))
      (font-lock-doc-markup-face ((t (:foreground ,cyan))))
      (font-lock-function-name-face ((t (:foreground ,magenta))))
      (font-lock-function-call-face ((t (:foreground ,magenta))))
      (font-lock-keyword-face ((t (:foreground ,red))))
      (font-lock-negation-char-face ((t (:foreground ,red))))
      (font-lock-preprocessor-face ((t (:foreground ,red))))
      (font-lock-regexp-face ((t (:foreground ,green))))
      (font-lock-regexp-grouping-backslash ((t (:foreground ,green))))
      (font-lock-regexp-grouping-construct ((t (:foreground ,magenta))))
      (font-lock-string-face ((t (:foreground ,green))))
      (font-lock-type-face ((t (:foreground ,magenta))))
      (font-lock-variable-name-face ((t (:foreground ,fg))))
      (font-lock-variable-use-face ((t (:foreground ,fg))))
      (font-lock-warning-face ((t (:foreground ,yellow :weight bold))))
      (font-lock-escape-face ((t (:foreground ,green))))
      (font-lock-number-face ((t (:foreground ,blue))))
      (font-lock-operator-face ((t (:foreground ,red))))
      (font-lock-property-name-face ((t (:foreground ,blue))))
      (font-lock-property-use-face ((t (:foreground ,blue))))
      (font-lock-bracket-face ((t (:foreground ,fg))))
      (font-lock-delimiter-face ((t (:foreground ,fg))))
      (font-lock-punctuation-face ((t (:foreground ,fg))))
      (font-lock-misc-punctuation-face ((t (:foreground ,fg))))

      ;; Tree-sitter capture faces used by tree-sitter based modes/packages.
      (tree-sitter-hl-face:attribute ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:boolean ((t (:foreground ,blue))))
      (tree-sitter-hl-face:comment ((t (:foreground ,muted))))
      (tree-sitter-hl-face:comment.doc ((t (:foreground ,muted))))
      (tree-sitter-hl-face:constant ((t (:foreground ,blue))))
      (tree-sitter-hl-face:constant.builtin ((t (:foreground ,blue))))
      (tree-sitter-hl-face:constructor ((t (:foreground ,green))))
      (tree-sitter-hl-face:embedded ((t (:foreground ,fg))))
      (tree-sitter-hl-face:emphasis ((t (:foreground ,fg :slant italic))))
      (tree-sitter-hl-face:emphasis.strong ((t (:foreground ,fg :weight bold))))
      (tree-sitter-hl-face:enum ((t (:foreground ,blue))))
      (tree-sitter-hl-face:escape ((t (:foreground ,green))))
      (tree-sitter-hl-face:function ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:function.builtin ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:function.call ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:function.macro ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:function.method ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:function.method.call ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:function.special ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:hint ((t (:foreground ,muted))))
      (tree-sitter-hl-face:keyword ((t (:foreground ,red))))
      (tree-sitter-hl-face:label ((t (:foreground ,blue))))
      (tree-sitter-hl-face:link_text ((t (:foreground ,blue :underline t))))
      (tree-sitter-hl-face:link_uri ((t (:foreground ,blue :underline t))))
      (tree-sitter-hl-face:method ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:method.call ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:number ((t (:foreground ,blue))))
      (tree-sitter-hl-face:operator ((t (:foreground ,red))))
      (tree-sitter-hl-face:predictive ((t (:foreground ,ignored))))
      (tree-sitter-hl-face:preproc ((t (:foreground ,red))))
      (tree-sitter-hl-face:primary ((t (:foreground ,fg))))
      (tree-sitter-hl-face:property ((t (:foreground ,blue))))
      (tree-sitter-hl-face:property.definition ((t (:foreground ,blue))))
      (tree-sitter-hl-face:punctuation ((t (:foreground ,fg))))
      (tree-sitter-hl-face:punctuation.bracket ((t (:foreground ,fg))))
      (tree-sitter-hl-face:punctuation.delimiter ((t (:foreground ,fg))))
      (tree-sitter-hl-face:punctuation.list_marker ((t (:foreground ,fg))))
      (tree-sitter-hl-face:punctuation.special ((t (:foreground ,red))))
      (tree-sitter-hl-face:string ((t (:foreground ,green))))
      (tree-sitter-hl-face:string.escape ((t (:foreground ,green))))
      (tree-sitter-hl-face:string.regex ((t (:foreground ,green))))
      (tree-sitter-hl-face:string.special ((t (:foreground ,green))))
      (tree-sitter-hl-face:string.special.symbol ((t (:foreground ,green))))
      (tree-sitter-hl-face:tag ((t (:foreground ,green))))
      (tree-sitter-hl-face:tag.doctype ((t (:foreground ,green))))
      (tree-sitter-hl-face:text.literal ((t (:foreground ,green))))
      (tree-sitter-hl-face:title ((t (:foreground ,blue))))
      (tree-sitter-hl-face:type ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:type.builtin ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:type.parameter ((t (:foreground ,magenta))))
      (tree-sitter-hl-face:variable ((t (:foreground ,fg))))
      (tree-sitter-hl-face:variable.builtin ((t (:foreground ,blue))))
      (tree-sitter-hl-face:variable.parameter ((t (:foreground ,fg))))
      (tree-sitter-hl-face:variable.special ((t (:foreground ,blue))))
      (tree-sitter-hl-face:variant ((t (:foreground ,blue))))


      (ansi-color-black ((t (:foreground ,black :background ,black))))
      (ansi-color-red ((t (:foreground ,red :background ,red))))
      (ansi-color-green ((t (:foreground ,green :background ,green))))
      (ansi-color-yellow ((t (:foreground ,yellow :background ,yellow))))
      (ansi-color-blue ((t (:foreground ,blue :background ,blue))))
      (ansi-color-magenta ((t (:foreground ,magenta :background ,magenta))))
      (ansi-color-cyan ((t (:foreground ,cyan :background ,cyan))))
      (ansi-color-white ((t (:foreground ,white :background ,white))))
      (ansi-color-bright-black ((t (:foreground ,bright-black :background ,bright-black))))
      (ansi-color-bright-red ((t (:foreground ,red :background ,red))))
      (ansi-color-bright-green ((t (:foreground ,green :background ,green))))
      (ansi-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
      (ansi-color-bright-blue ((t (:foreground ,blue :background ,blue))))
      (ansi-color-bright-magenta ((t (:foreground ,magenta :background ,magenta))))
      (ansi-color-bright-cyan ((t (:foreground ,cyan :background ,cyan))))
      (ansi-color-bright-white ((t (:foreground ,bright-white :background ,bright-white))))
      (term-color-black ((t (:foreground ,black :background ,black))))
      (term-color-red ((t (:foreground ,red :background ,red))))
      (term-color-green ((t (:foreground ,green :background ,green))))
      (term-color-yellow ((t (:foreground ,yellow :background ,yellow))))
      (term-color-blue ((t (:foreground ,blue :background ,blue))))
      (term-color-magenta ((t (:foreground ,magenta :background ,magenta))))
      (term-color-cyan ((t (:foreground ,cyan :background ,cyan))))
      (term-color-white ((t (:foreground ,white :background ,white))))
      (vterm-color-black ((t (:foreground ,black :background ,black))))
      (vterm-color-red ((t (:foreground ,red :background ,red))))
      (vterm-color-green ((t (:foreground ,green :background ,green))))
      (vterm-color-yellow ((t (:foreground ,yellow :background ,yellow))))
      (vterm-color-blue ((t (:foreground ,blue :background ,blue))))
      (vterm-color-magenta ((t (:foreground ,magenta :background ,magenta))))
      (vterm-color-cyan ((t (:foreground ,cyan :background ,cyan))))
      (vterm-color-white ((t (:foreground ,white :background ,white))))
      (ghostel-color-black ((t (:foreground ,black :background ,black))))
      (ghostel-color-red ((t (:foreground ,red :background ,red))))
      (ghostel-color-green ((t (:foreground ,green :background ,green))))
      (ghostel-color-yellow ((t (:foreground ,yellow :background ,yellow))))
      (ghostel-color-blue ((t (:foreground ,blue :background ,blue))))
      (ghostel-color-magenta ((t (:foreground ,magenta :background ,magenta))))
      (ghostel-color-cyan ((t (:foreground ,cyan :background ,cyan))))
      (ghostel-color-white ((t (:foreground ,white :background ,white))))
      (ghostel-color-bright-black ((t (:foreground ,bright-black :background ,bright-black))))
      (ghostel-color-bright-red ((t (:foreground ,red :background ,red))))
      (ghostel-color-bright-green ((t (:foreground ,green :background ,green))))
      (ghostel-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
      (ghostel-color-bright-blue ((t (:foreground ,blue :background ,blue))))
      (ghostel-color-bright-magenta ((t (:foreground ,magenta :background ,magenta))))
      (ghostel-color-bright-cyan ((t (:foreground ,cyan :background ,cyan))))
      (ghostel-color-bright-white ((t (:foreground ,bright-white :background ,bright-white))))
      (comint-highlight-prompt ((t (:foreground ,blue :weight bold))))
      (comint-highlight-input ((t (:foreground ,fg))))

      (dired-directory ((t (:foreground ,blue :weight bold))))
      (dired-symlink ((t (:foreground ,cyan))))
      (dired-flagged ((t (:foreground ,red :weight bold))))
      (dired-marked ((t (:foreground ,magenta :weight bold))))
      (dired-header ((t (:foreground ,blue :weight bold))))
      (dired-ignored ((t (:foreground ,ignored))))

      (diff-added ((t (:background ,success-bg :foreground ,green :extend t))))
      (diff-removed ((t (:background ,error-bg :foreground ,red :extend t))))
      (diff-changed ((t (:background ,warning-bg :foreground ,yellow :extend t))))
      (diff-refine-added ((t (:background ,green :foreground ,inverse-fg))))
      (diff-refine-removed ((t (:background ,red :foreground ,inverse-fg))))
      (diff-refine-changed ((t (:background ,yellow :foreground ,inverse-fg))))
      (diff-header ((t (:background ,surface :foreground ,fg :extend t))))
      (diff-file-header ((t (:background ,surface :foreground ,blue :weight bold :extend t))))
      (diff-hunk-header ((t (:background ,element :foreground ,magenta :extend t))))
      (diff-hl-insert ((t (:foreground ,green :background ,green))))
      (diff-hl-delete ((t (:foreground ,red :background ,red))))
      (diff-hl-change ((t (:foreground ,yellow :background ,yellow))))
      (magit-section-heading ((t (:foreground ,blue :weight bold))))
      (magit-section-highlight ((t (:background ,hover :extend t))))
      (magit-branch-local ((t (:foreground ,blue))))
      (magit-branch-remote ((t (:foreground ,green))))
      (magit-tag ((t (:foreground ,yellow))))
      (magit-hash ((t (:foreground ,ignored))))
      (magit-dimmed ((t (:foreground ,muted))))
      (magit-diff-file-heading ((t (:foreground ,blue :weight bold))))
      (magit-diff-hunk-heading ((t (:background ,element :foreground ,magenta :extend t))))
      (magit-diff-added ((t (:background ,success-bg :foreground ,green :extend t))))
      (magit-diff-removed ((t (:background ,error-bg :foreground ,red :extend t))))

      (flycheck-error ((t (:underline (:style wave :color ,red)))))
      (flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
      (flycheck-info ((t (:underline (:style wave :color ,blue)))))
      (flymake-error ((t (:underline (:style wave :color ,red)))))
      (flymake-warning ((t (:underline (:style wave :color ,yellow)))))
      (flymake-note ((t (:underline (:style wave :color ,blue)))))
      (lsp-face-highlight-read ((t (:background ,selection :extend t))))
      (lsp-face-highlight-write ((t (:background ,success-bg :extend t))))
      (lsp-face-highlight-textual ((t (:background ,hover :extend t))))
      (lsp-inlay-hint-face ((t (:background ,inlay-bg :foreground ,muted :height 0.9))))
      (lsp-inlay-hint-parameter-face ((t (:background ,inlay-bg :foreground ,muted :height 0.9))))
      (lsp-inlay-hint-type-face ((t (:background ,inlay-bg :foreground ,muted :height 0.9))))
      (lsp-lens-face ((t (:foreground ,muted :height 0.85))))
      (lsp-face-semhl-comment ((t (:foreground ,muted))))
      (lsp-face-semhl-function ((t (:foreground ,magenta))))
      (lsp-face-semhl-method ((t (:foreground ,magenta))))
      (lsp-face-semhl-macro ((t (:foreground ,magenta))))
      (lsp-face-semhl-keyword ((t (:foreground ,red))))
      (lsp-face-semhl-operator ((t (:foreground ,red))))
      (lsp-face-semhl-string ((t (:foreground ,green))))
      (lsp-face-semhl-regexp ((t (:foreground ,green))))
      (lsp-face-semhl-number ((t (:foreground ,blue))))
      (lsp-face-semhl-type ((t (:foreground ,magenta))))
      (lsp-face-semhl-class ((t (:foreground ,magenta))))
      (lsp-face-semhl-struct ((t (:foreground ,magenta))))
      (lsp-face-semhl-interface ((t (:foreground ,magenta))))
      (lsp-face-semhl-enum ((t (:foreground ,magenta))))
      (lsp-face-semhl-type-parameter ((t (:foreground ,magenta))))
      (lsp-face-semhl-variable ((t (:foreground ,fg))))
      (lsp-face-semhl-parameter ((t (:foreground ,fg))))
      (lsp-face-semhl-property ((t (:foreground ,blue))))
      (lsp-face-semhl-member ((t (:foreground ,blue))))
      (lsp-face-semhl-event ((t (:foreground ,blue))))
      (lsp-face-semhl-constant ((t (:foreground ,blue))))
      (lsp-face-semhl-namespace ((t (:foreground ,blue))))
      (lsp-face-semhl-label ((t (:foreground ,blue))))
      (lsp-face-semhl-default-library ((t (:foreground ,magenta))))
      (lsp-face-semhl-definition ((t (:foreground ,magenta :weight bold))))
      (lsp-face-semhl-implementation ((t (:foreground ,magenta :weight bold))))
      (lsp-face-semhl-static ((t (:foreground ,blue))))
      (lsp-face-semhl-deprecated ((t (:foreground ,muted :strike-through t))))

      (vertico-current ((t (:background ,hover :extend t))))
      (vertico-group-title ((t (:foreground ,muted :slant italic))))
      (vertico-group-separator ((t (:foreground ,border :strike-through t))))
      (marginalia-documentation ((t (:foreground ,muted))))
      (marginalia-key ((t (:foreground ,blue))))
      (marginalia-function ((t (:foreground ,magenta))))
      (marginalia-string ((t (:foreground ,green))))
      (marginalia-number ((t (:foreground ,blue))))
      (consult-highlight-match ((t (:inherit match))))
      (consult-preview-match ((t (:inherit match))))
      (consult-separator ((t (:foreground ,border))))
      (orderless-match-face-0 ((t (:foreground ,blue :weight bold))))
      (orderless-match-face-1 ((t (:foreground ,magenta :weight bold))))
      (orderless-match-face-2 ((t (:foreground ,green :weight bold))))
      (orderless-match-face-3 ((t (:foreground ,yellow :weight bold))))
      (which-key-key-face ((t (:foreground ,blue :weight bold))))
      (which-key-command-description-face ((t (:foreground ,fg))))
      (which-key-group-description-face ((t (:foreground ,magenta))))
      (transient-heading ((t (:foreground ,blue :weight bold))))
      (transient-key ((t (:foreground ,magenta :weight bold))))
      (transient-argument ((t (:foreground ,green))))
      (corfu-default ((t (:background ,surface :foreground ,fg))))
      (corfu-current ((t (:background ,hover :foreground ,fg))))
      (corfu-border ((t (:background ,border))))
      (company-tooltip ((t (:background ,surface :foreground ,fg))))
      (company-tooltip-selection ((t (:background ,hover :foreground ,fg))))

      (outline-1 ((t (:foreground ,blue :weight bold))))
      (outline-2 ((t (:foreground ,magenta :weight bold))))
      (outline-3 ((t (:foreground ,green :weight bold))))
      (outline-4 ((t (:foreground ,yellow :weight bold))))
      (outline-5 ((t (:foreground ,cyan :weight bold))))
      (outline-6 ((t (:foreground ,red :weight bold))))

      ;; The original Vercel theme does not rainbow-color delimiters; keep them
      ;; close to normal text while preserving error highlighting.
      (rainbow-delimiters-depth-1-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-2-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-3-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-4-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-5-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-6-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-7-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-8-face ((t (:foreground ,fg))))
      (rainbow-delimiters-depth-9-face ((t (:foreground ,fg))))
      (rainbow-delimiters-mismatched-face ((t (:foreground ,red :weight bold))))
      (rainbow-delimiters-unmatched-face ((t (:foreground ,red :weight bold)))))))

(defun vercel-theme--variables (palette)
  "Return Vercel custom variable specs derived from PALETTE."
  (chief-theme-kit-with-colors palette
      (black red green yellow blue magenta cyan bright-white)
    `((ansi-color-names-vector [,black ,red ,green ,yellow ,blue ,magenta ,cyan ,bright-white]))))

(defun vercel-theme-apply (theme palette)
  "Apply Vercel face and variable specs for THEME from PALETTE."
  (chief-theme-kit-apply theme
                         (vercel-theme--faces palette)
                         (vercel-theme--variables palette)))

(provide 'vercel-theme-support)

;;; vercel-theme-support.el ends here
